spring:
  application:
    name: provider-goods-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/trade?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 192.168.247.145:9876;192.168.247.145:9877
      bindings:
        order-in2: {destination: order-out, content-type: application/json, group: order-out-group2, consumer.maxAttempts: 1}
dubbo:
  scan:
    base-packages: com.zzp.shop.provider.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://192.168.247.145
    port: 8848

mybatis:
  type-aliases-package: com.zzp.shop.provider.domain
  mapper-locations: classpath:mapper/*.xml
debug: true

logging:
  level:
    com.zzp.shop.provider.mapper: debug
